### ISSUE TITLE
End line added to Solidity code blocks in Markdown files

### ISSUE THREAD

**Issue by paulrberg** [prettier-solidity/prettier-plugin-solidity#764]
## Description

This is exactly the same issue as https://github.com/prettier/prettier-vscode/issues/624, but none of the workarounds mentioned there work for `prettier-plugin-solidity`.

## Current Behavior

`prettier-plugin-solidity` adds an extra new line in Solidity code blocks in Markdown files. For instance, take this simple script:

\```solidity
import "./Foo.sol";
\```

An extra new line will be added on the second line, turning the script into this:

\```solidity
import "./Foo.sol";

\```

## Expected Behavior

I would prefer `prettier-plugin-solidity` not to add an extra line in Markdown code blocks. Even better, not to apply any formatting rules (by letting me disable them), because I may want to explicitly avoid many of the usual formatting rules in presentational code snippets.

## Environment

- prettier v2.8.0
- prettier-plugin-solidity v1.0.0

And this is my Prettier configuration:

```yml
bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false
```
